version: "3.9"
 
services:
  app:
    image: ./Dockerfile
    command: python -m http.server 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
